export const actionTypes = {
    REQUEST_ACTION: 'REQUEST_ACTION',
    SUCCESS_ACTION: 'SUCCESS_ACTION',
    FAILED_ACTION:  'FAILED_ACTION',
    IDLE_ACTION : "IDLE_ACTION",
    RESET_ALL:'RESET_ALL',
}