export const USER_NAME = "user name should be letters,symboles,nums"
export const PASSWORD = "password should be up to 5 charactors"
export const TEXT = "only letters"
export const TEL = "only numbers and max 8 chars , 76xxxxxx"
export const EMAIL = "Invalid email" 
export const TEXT_NUMBER = "only text and nmbers" 